# Generated by Django 3.2.5 on 2022-10-07 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField()),
                ('test_name', models.CharField(max_length=30)),
                ('test_type', models.CharField(max_length=30)),
                ('test_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('test_image', models.ImageField(blank=True, upload_to='noticeboard/image/%Y/%M/%D')),
            ],
        ),
    ]
